### PR TITLE
Issue3357 - Strip trailing slash on exchange url

### LINKED ISSUE #3357: Bug: agent-install.sh fails if HZN_EXCHANGE_URL ends with "/v1/" (ie. trailing slash)
### Describe the bug.

In the master branch, if a user the exchange url defined with a trailing / such as
HZN_EXCHANGE_URL=http://9.1.0.1:3090/v1/

the function check_exch_url_and_cert in agent-install.sh will fail because the curl will fail

We should check to see if it ends with a trailing slash and fix it up so the rest of agent-install.sh will succeed.
It was difficult to debug why it was failing

### Describe the steps to reproduce the behavior.

See above steps

### Expected behavior.

agent-install.sh should work if the HZN_EXCHANGE_URL ends with a trailing /

### Screenshots.

_No response_

### Operating Environment

ubuntu

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dlarson04**
Signed-off-by: Doug Larson <larsond@us.ibm.com>

# Pull Request Template

## Description

Strip trailing / from HZN_EXCHANGE_URL if it exists to prevent the curl command from failing

Fixes #3357 

## Type of change

Please delete options that are not relevant.

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Built and tested with a w/o a trailing slash

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x ] I have checked my code and corrected any misspellings
- [x ] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

File: agent-install/agent-install.sh [hunk 1]
```diff
@@ -2995,7 +2995,16 @@ function check_exch_url_and_cert() {
...
+    local TMP_HZN_EXCHANGE_URL=$HZN_EXCHANGE_URL
+    if [[ "$TMP_HZN_EXCHANGE_URL" != "" ]]; then
+	    LAST_CHAR=(${TMP_HZN_EXCHANGE_URL: -1})
+	    # If this URL ends with "/" the curl command will fail... remove the trailing / if it exists
+	    if [[ "$LAST_CHAR" == "/" ]]; then
+		    TMP_HZN_EXCHANGE_URL=${TMP_HZN_EXCHANGE_URL%?}
+	    fi
+    fi
+
+    local output=$(curl -w %{http_code} -fsS $cert_flag $TMP_HZN_EXCHANGE_URL/admin/version 2>/dev/null) || true
```
Comment (linggao) [inline agent-install/agent-install.sh:3007]: Good catch, can you also fix the same error for ling 2972 and 465?

Comment (dlarson04) [reply agent-install/agent-install.sh]: Resolved.. Changed the URL higher up  so other places will not fail

**Review by linggao — APPROVED** [review]
