### PR TITLE
Issue 3318 - Bug: Manifests published by hzn man add CLI command not being digitally signed

### LINKED ISSUE #3318: Bug: Manifests published by  hzn man add CLI command not being digitally signed
### Describe the bug.

Manifests published by  hzn man add CLI command not being digitally signed

### Describe the steps to reproduce the behavior.

_No response_

### Expected behavior.

_No response_

### Screenshots.

_No response_

### Operating Environment

ubuntu

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Polber**
Signed-off-by: Jeff Kinard <jeff@thekinards.com>

# Pull Request Template

## Description

This PR adds digital signing to manifest uploads to the CSS. This was a feature already implemented for model uploads, so it was refactored to support manifests as well.

Fixes #3318 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

This was tested by uploading a manifest using the `hzn nm man add` command (which now has digital signing), and running a NMP upgrade to make sure it did not break the NMP process. The `hzn mms obj pub` command was also tested to make sure it worked as before.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

File: cli/sync_service/object.go [hunk 1]
```diff
@@ -353,13 +353,18 @@ func ObjectPublish(org string, userPw string, objType string, objId string, objP
 		msgPrinter.Printf("Digital sign with %s will be performed for data integrity. It will delay the MMS object publish.\n", hashAlgorithm)
 
 		// Create public key. Sign data. Set "hashAlgorithm", "publicKey" and "signature" field
-		if publicKey, signature, err := signObjData(objFile, hashAlgorithm, dsHash, privKeyFilePath); err != nil {
+		file, err := os.Open(objFile)
+		if err != nil {
+			cliutils.Fatal(cliutils.CLI_INPUT_ERROR, msgPrinter.Sprintf("unable to open object file %v: %v", objFile, err))
+		}
+		if publicKey, signature, err := SignObjData(file, hashAlgorithm, dsHash, privKeyFilePath); err != nil {
```
Comment (LiilyZhang) [inline cli/sync_service/object.go:360]: should we close the flie `file.Close()` here before giving back error?

Comment (Polber) [reply cli/sync_service/object.go:361]: Changed to a `defer file.Close()` statement
