### PR TITLE
Issue 3121 - AgentAutoUpgrade: Fix path to status.json in k8s cronjob script

### LINKED ISSUE #3121: AgentAutoUpgrade: Fix path to status.json in k8s cronjob script
The path to the status.json script is currently /var/horizon/status.json, but should be /var/horizon/{org}/{nmp-name}/status.json

### PR DESCRIPTION
**Pull request by Polber**
Signed-off-by: Jeff Kinard <jeff@thekinards.com>

## Description

This PR introduces several changes to the edge cluster agent in order for the auto agent rollback cronjob to function properly...

1. The cronjob pod now mounts itself to the same /var/horizon PVC directory as the agent pod so that it can read/write the status.json file directly
        - This also meant changing the permissions on the PVC from `ReadWriteOnce` to `ReadWriteMany` so that more than one pod can mount to it
2. The cronjob now looks for the status.json file in the path `/var/horizon/nmp/{org}/{nmp-name}/status.json`
        - It will loop through all the directories in the `/var/horizon/nmp/{org}/` path to find the status.json that has the latest `startTime` field. This way it is always working on the last ran auto upgrade job. 
3. The cronjob will now delete itself upon success or failure (without attempting to restart itself on failure), but it will write its logs to `/var/horizon/cronjob.log` before exiting, and keep the last 1 million lines.
4. `agent-uninstall.sh` now removes the cronjob before removing the PVC since the PVC is now mounted to the cronjob (to prevent stalling on uninstall)

Fixes #3121

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

This was tested by installing the new cronjob image and running through the new changes manually to make sure they work as expected.

1. Manually check that it picks up the most recent job when there are multiple NMP directories in `/var/horizon/nmp/{org}`
2. Manually check that it exits early if there are no jobs, or all jobs have completed
3. Manually check that it throws an error if there are multiple org directories in `/var/horizon/nmp`
4. Manually check that it exits early if there is no `/var/horizon/nmp` or `/var/horizon/nmp/{org}` directories
5. Manually check that the cronjob does not try to rollback (restart) when it exits with a non-zero exit code
6. Manually check that all logs are recorded to `/var/horizon/cronjob.log`
7. Manually check that `agent-uninstall.sh` works

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

File: anax-in-k8s/cronjobs/auto-upgrade-cronjob.sh [hunk 1]
```diff
@@ -245,91 +283,204 @@ function rollback_agent_image() {
...
+# Check deployment/pod status
 log_info "Checking if agent is running and deployment is successful..."
 if [[ "$pod_status" != "Running" || "$dep_status" != "Running" ]]; then
     
-    # If k8s deployment status is "error" and if status.json has "rollback started" -> set status to "rollback failed" (stop here)
+    # Should never happen, but if k8s deployment status is "error" and if status.json has "rollback started", set status to "rollback failed" and exit
     log_info "Agent is not running. Checking if rollback was already attempted..."
-    if [[ "$json_status" == "rollback started" ]]; then
+    if [[ "$json_status" == "$STATUS_ROLLBACK_STARTED" ]]; then
         rollback_failed "Rollback was already initiated, but it failed. Deployment status: $dep_status"
```
Comment (LiilyZhang) [inline anax-in-k8s/cronjobs/auto-upgrade-cronjob.sh:413]: Can you wait $AGENT_DEPLOYMENT_STATUS_TIMEOUT_SECONDS (right now it sets to 75s) before calling `rollback_failed` function at here:
```
 if [[ "$json_status" == "$STATUS_ROLLBACK_STARTED" ]]; then
    wait for 75s
    rollback_failed "Rollback was already initiated, but it failed. Deployment status: $dep_status"
fi
```

Because  `pod/deploy status != Running` doesn't mean it fail, maybe it is just slow to bring up pod.

File: anax-in-k8s/cronjobs/auto-upgrade-cronjob.sh [hunk 2]
```diff
@@ -245,91 +283,204 @@ function rollback_agent_image() {
...
+        exit 0
+    fi
+
+    # Loop through NMP subdirectories and check each status.json for newest job that needs rollback
+    log_verbose "Getting latest upgrade job status file..."
+    local latest
+    latest=-1
+    local filepath
+    filepath=/var/horizon/nmp/$nmp_org
+    STATUS_PATH=/var/horizon/nmp/fake_org/fake_nmp/status.json
```
Comment (LiilyZhang) [inline anax-in-k8s/cronjobs/auto-upgrade-cronjob.sh:337]: Are the fake_org and fake_nmp just for testing?

File: anax-in-k8s/cronjobs/auto-upgrade-cronjob.sh [hunk 3]
```diff
@@ -344,17 +495,13 @@ if [[ $image_updated == "true" ]]; then
...
-        rollback_failed "There was an unexpected error while restarting agent pod: $cmd_output"
-    fi
+    restart_agent_pod
+    check_deployment_status
 fi
 
 # If the rollback ran successfully, update status to "rollback successful". 
 log_verbose "Setting the status to \"rollback successful\"..."
-agent_cmd "sed -i 's/\"status\":.*/\"status\": \"rollback successful\",/g' /var/horizon/status.json"
+sed -i 's/\"status\":.*/\"status\": \"rollback successful\",/g' $STATUS_PATH
```
Comment (LiilyZhang) [inline anax-in-k8s/cronjobs/auto-upgrade-cronjob.sh:504]: Use `$STATUS_ROLLBACK_SUCCESSFUL` instead of "rollback successful" is better

File: anax-in-k8s/cronjobs/auto-upgrade-cronjob.sh (hunk 1 above)
Comment (Polber) [reply anax-in-k8s/cronjobs/auto-upgrade-cronjob.sh:413]: That's a good catch. I'm adding that

File: anax-in-k8s/cronjobs/auto-upgrade-cronjob.sh (hunk 2 above)
Comment (Polber) [reply anax-in-k8s/cronjobs/auto-upgrade-cronjob.sh:337]: I did that just to default it to a file that does not exist, but I can just set it to an empty string. Not sure why I didn't do that before

**Review by LiilyZhang — APPROVED** [review]
