### PR TITLE
Issue 3139 - fix missing msgprinter statements for i18n

### LINKED ISSUE #3139: fix missing msgprinter statements for i18n

### PR DESCRIPTION
**Pull request by Polber**
Signed-off-by: Jeff Kinard <jeff@thekinards.com>

## Description

This PR fixes all known instances of English output being printed to console that was not first translated by running through the i18n message printer.

Fixes #3139

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

This code is already known to work, so it did not need to be tested. The codebase already runs all hardcoded strings through the message printer, and the changes here do simply that.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

File: cli/sdo/voucher.go [hunk 1]
```diff
@@ -303,7 +305,7 @@ func VoucherDownload(org, userCreds, device, outputFile string, overwrite bool)
 	// Download response body directly to file
 	if outputFile != "" {
 		fileName := cliutils.DownloadToFile(outputFile, device, respBodyBytes, ".json", 0600, overwrite)
-		fmt.Printf("Voucher \"%s\" successfully downloaded to %s from the SDO owner services.\n", device, fileName)
+		fmt.Printf(msgPrinter.Sprintf("Voucher \"%s\" successfully downloaded to %s from the SDO owner services.\n", device, fileName))
```
Comment (linggao) [inline cli/sdo/voucher.go:308]: Remove the `\n` from the message, this one can be changed to 
````
msgPrinter.Printf("Voucher \"%s\" successfully downloaded to %s from the SDO owner services.", device, fileName)
msgPrinter.Println()
````

File: cli/dev/dependency.go [hunk 2]
```diff
@@ -112,19 +112,19 @@ func DependencyFetch(homeDirectory string, project string, specRef string, url s
 	// Check input parameters for correctness.
 	dir, err := verifyFetchInput(homeDirectory, project, specRef, url, org, version, arch, userCreds)
 	if err != nil {
-		cliutils.Fatal(cliutils.CLI_INPUT_ERROR, "'dependency %v' %v", DEPENDENCY_FETCH_COMMAND, err)
+		cliutils.Fatal(cliutils.CLI_INPUT_ERROR, msgPrinter.Sprintf("'dependency %v' %v", DEPENDENCY_FETCH_COMMAND, err))
```
Comment (linggao) [inline cli/dev/dependency.go:115]: No need to i18ning this string because `dependency` is the subcommand name. Same for all the changes in this file.

**Review by linggao — APPROVED** [review]
